// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlF9wj-PGvzVptr0jeR-Ov1m-1PwVhnKo',
    appId: '1:484578026292:web:390e1a57993d2c51453b61',
    messagingSenderId: '484578026292',
    projectId: 'wondersri-98260',
    authDomain: 'wondersri-98260.firebaseapp.com',
    storageBucket: 'wondersri-98260.firebasestorage.app',
    measurementId: 'G-7NZ1GT7XWX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKKDL84kCAjoFfvT2drzEaqoVATp3WJh4',
    appId: '1:484578026292:android:a60901f6bedc16b3453b61',
    messagingSenderId: '484578026292',
    projectId: 'wondersri-98260',
    storageBucket: 'wondersri-98260.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCprdFgeS4HNyd9PlL9AWrestHFOkSXV00',
    appId: '1:484578026292:ios:b1ea7b8035693736453b61',
    messagingSenderId: '484578026292',
    projectId: 'wondersri-98260',
    storageBucket: 'wondersri-98260.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCprdFgeS4HNyd9PlL9AWrestHFOkSXV00',
    appId: '1:484578026292:ios:b1ea7b8035693736453b61',
    messagingSenderId: '484578026292',
    projectId: 'wondersri-98260',
    storageBucket: 'wondersri-98260.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAlF9wj-PGvzVptr0jeR-Ov1m-1PwVhnKo',
    appId: '1:484578026292:web:b6ee8e3572a10ba9453b61',
    messagingSenderId: '484578026292',
    projectId: 'wondersri-98260',
    authDomain: 'wondersri-98260.firebaseapp.com',
    storageBucket: 'wondersri-98260.firebasestorage.app',
    measurementId: 'G-JE4RTY9QHF',
  );
}
