name: Flutter CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.0'

      - name: Install Dependencies
        run: flutter pub get

      - name: Set environment variables from secrets
        run: |
            echo "MY_API_KEY=${{ secrets.MY_API_KEY }}" >> $GITHUB_ENV
            echo "DIRECTION_API_KEY=${{ secrets.DIRECTION_API_KEY }}" >> $GITHUB_ENV

      - name: Run Tests
        run: flutter test
        continue-on-error: true

      - name: Build Release APK
        run: flutter build apk --release
        continue-on-error: true

      - name: Create artifact directory
        run: mkdir -p /tmp/artifacts

      - name: Copy APK to artifacts directory
        run: cp build/app/outputs/flutter-apk/app-release.apk /tmp/artifacts/

      - name: Upload artifact 
        run: |
          gh api -X POST \
            /repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts \
            -F name="release-apk" \
            -F data=@/tmp/artifacts/app-release.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
